
package com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InvoiceInterfaceService", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/", wsdlLocation = "https://eggx-test.fa.us6.oraclecloud.com:443/fscmService/InvoiceInterfaceService?wsdl")
public class InvoiceInterfaceService_Service
    extends Service
{

    private final static URL INVOICEINTERFACESERVICE_WSDL_LOCATION;
    private final static WebServiceException INVOICEINTERFACESERVICE_EXCEPTION;
    private final static QName INVOICEINTERFACESERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/", "InvoiceInterfaceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://eggx-test.fa.us6.oraclecloud.com:443/fscmService/InvoiceInterfaceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVOICEINTERFACESERVICE_WSDL_LOCATION = url;
        INVOICEINTERFACESERVICE_EXCEPTION = e;
    }

    public InvoiceInterfaceService_Service() {
        super(__getWsdlLocation(), INVOICEINTERFACESERVICE_QNAME);
    }

    public InvoiceInterfaceService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVOICEINTERFACESERVICE_QNAME, features);
    }

    public InvoiceInterfaceService_Service(URL wsdlLocation) {
        super(wsdlLocation, INVOICEINTERFACESERVICE_QNAME);
    }

    public InvoiceInterfaceService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVOICEINTERFACESERVICE_QNAME, features);
    }

    public InvoiceInterfaceService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InvoiceInterfaceService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InvoiceInterfaceService
     */
    @WebEndpoint(name = "InvoiceInterfaceServiceSoapHttpPort")
    public InvoiceInterfaceService getInvoiceInterfaceServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/", "InvoiceInterfaceServiceSoapHttpPort"), InvoiceInterfaceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InvoiceInterfaceService
     */
    @WebEndpoint(name = "InvoiceInterfaceServiceSoapHttpPort")
    public InvoiceInterfaceService getInvoiceInterfaceServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/", "InvoiceInterfaceServiceSoapHttpPort"), InvoiceInterfaceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVOICEINTERFACESERVICE_EXCEPTION!= null) {
            throw INVOICEINTERFACESERVICE_EXCEPTION;
        }
        return INVOICEINTERFACESERVICE_WSDL_LOCATION;
    }

}
