
package com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.xmlns.adf.svc.types.FindControl;
import com.oracle.xmlns.adf.svc.types.FindCriteria;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InvoiceInterfaceService", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/")
@XmlSeeAlso({
    com.oracle.xmlns.adf.svc.errors.ObjectFactory.class,
    com.oracle.xmlns.adf.svc.types.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.ObjectFactory.class,
    com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class,
    sdo.commonj.ObjectFactory.class,
    sdo.commonj.java.ObjectFactory.class,
    sdo.commonj.xml.ObjectFactory.class
})
public interface InvoiceInterfaceService {


    /**
     * 
     * @param invoiceInterfaceHeader
     * @return
     *     returns com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.InvoiceInterfaceHeaderResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/createInvoiceInterface")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
    @RequestWrapper(localName = "createInvoiceInterface", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.CreateInvoiceInterface")
    @ResponseWrapper(localName = "createInvoiceInterfaceResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.CreateInvoiceInterfaceResponse")
    public InvoiceInterfaceHeaderResult createInvoiceInterface(
        @WebParam(name = "invoiceInterfaceHeader", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        InvoiceInterfaceHeader invoiceInterfaceHeader)
        throws ServiceException
    ;

    /**
     * 
     * @param invoiceInterfaceHeader
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/createInvoiceInterfaceAsync")
    @Oneway
    @RequestWrapper(localName = "createInvoiceInterfaceAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.CreateInvoiceInterfaceAsync")
    public void createInvoiceInterfaceAsync(
        @WebParam(name = "invoiceInterfaceHeader", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        InvoiceInterfaceHeader invoiceInterfaceHeader);

    /**
     * 
     * @param ledgerId
     * @param groupName
     * @param accountingDate
     * @param holdReason
     * @param summarizeReport
     * @param importSet
     * @param orgId
     * @param hold
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/submitInvoiceImport")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
    @RequestWrapper(localName = "submitInvoiceImport", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.SubmitInvoiceImport")
    @ResponseWrapper(localName = "submitInvoiceImportResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.SubmitInvoiceImportResponse")
    public String submitInvoiceImport(
        @WebParam(name = "ledgerId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        long ledgerId,
        @WebParam(name = "orgId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        long orgId,
        @WebParam(name = "importSet", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        String importSet,
        @WebParam(name = "groupName", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        String groupName,
        @WebParam(name = "accountingDate", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        XMLGregorianCalendar accountingDate,
        @WebParam(name = "hold", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        String hold,
        @WebParam(name = "holdReason", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        String holdReason,
        @WebParam(name = "summarizeReport", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        String summarizeReport)
        throws ServiceException
    ;

    /**
     * 
     * @param ledgerId
     * @param groupName
     * @param accountingDate
     * @param holdReason
     * @param summarizeReport
     * @param importSet
     * @param orgId
     * @param hold
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/submitInvoiceImportAsync")
    @Oneway
    @RequestWrapper(localName = "submitInvoiceImportAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.SubmitInvoiceImportAsync")
    public void submitInvoiceImportAsync(
        @WebParam(name = "ledgerId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        long ledgerId,
        @WebParam(name = "orgId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        long orgId,
        @WebParam(name = "importSet", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        String importSet,
        @WebParam(name = "groupName", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        String groupName,
        @WebParam(name = "accountingDate", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        XMLGregorianCalendar accountingDate,
        @WebParam(name = "hold", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        String hold,
        @WebParam(name = "holdReason", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        String holdReason,
        @WebParam(name = "summarizeReport", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        String summarizeReport);

    /**
     * 
     * @param invoiceInterfaceHeader
     * @return
     *     returns com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.InterfaceResponseResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/createB2BInvoice")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
    @RequestWrapper(localName = "createB2BInvoice", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.CreateB2BInvoice")
    @ResponseWrapper(localName = "createB2BInvoiceResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.CreateB2BInvoiceResponse")
    public InterfaceResponseResult createB2BInvoice(
        @WebParam(name = "InvoiceInterfaceHeader", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        List<InvoiceInterfaceHeader> invoiceInterfaceHeader)
        throws ServiceException
    ;

    /**
     * 
     * @param invoiceInterfaceHeader
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/createB2BInvoiceAsync")
    @Oneway
    @RequestWrapper(localName = "createB2BInvoiceAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.CreateB2BInvoiceAsync")
    public void createB2BInvoiceAsync(
        @WebParam(name = "InvoiceInterfaceHeader", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        List<InvoiceInterfaceHeader> invoiceInterfaceHeader);

    /**
     * 
     * @param invoiceInterfaceHeader
     * @return
     *     returns com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.InvoiceInterfaceHeaderResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/updateInvoiceInterface")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
    @RequestWrapper(localName = "updateInvoiceInterface", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.UpdateInvoiceInterface")
    @ResponseWrapper(localName = "updateInvoiceInterfaceResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.UpdateInvoiceInterfaceResponse")
    public InvoiceInterfaceHeaderResult updateInvoiceInterface(
        @WebParam(name = "invoiceInterfaceHeader", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        InvoiceInterfaceHeader invoiceInterfaceHeader)
        throws ServiceException
    ;

    /**
     * 
     * @param invoiceInterfaceHeader
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/updateInvoiceInterfaceAsync")
    @Oneway
    @RequestWrapper(localName = "updateInvoiceInterfaceAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.UpdateInvoiceInterfaceAsync")
    public void updateInvoiceInterfaceAsync(
        @WebParam(name = "invoiceInterfaceHeader", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        InvoiceInterfaceHeader invoiceInterfaceHeader);

    /**
     * 
     * @param loadRequestId
     * @param invoiceId
     * @return
     *     returns com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.InvoiceInterfaceHeader
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/getInvoiceInterface")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
    @RequestWrapper(localName = "getInvoiceInterface", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.GetInvoiceInterface")
    @ResponseWrapper(localName = "getInvoiceInterfaceResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.GetInvoiceInterfaceResponse")
    public InvoiceInterfaceHeader getInvoiceInterface(
        @WebParam(name = "invoiceId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        long invoiceId,
        @WebParam(name = "loadRequestId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        long loadRequestId)
        throws ServiceException
    ;

    /**
     * 
     * @param findCriteria
     * @param findControl
     * @return
     *     returns com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.InvoiceInterfaceHeaderResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/findInvoiceInterface")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
    @RequestWrapper(localName = "findInvoiceInterface", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.FindInvoiceInterface")
    @ResponseWrapper(localName = "findInvoiceInterfaceResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.FindInvoiceInterfaceResponse")
    public InvoiceInterfaceHeaderResult findInvoiceInterface(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param loadRequestId
     * @param invoiceId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/getInvoiceInterfaceAsync")
    @Oneway
    @RequestWrapper(localName = "getInvoiceInterfaceAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.GetInvoiceInterfaceAsync")
    public void getInvoiceInterfaceAsync(
        @WebParam(name = "invoiceId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        long invoiceId,
        @WebParam(name = "loadRequestId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        long loadRequestId);

    /**
     * 
     * @param findCriteria
     * @param findControl
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/findInvoiceInterfaceAsync")
    @Oneway
    @RequestWrapper(localName = "findInvoiceInterfaceAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.FindInvoiceInterfaceAsync")
    public void findInvoiceInterfaceAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        FindControl findControl);

    /**
     * 
     * @param requestId
     * @param vendorEmailAddress
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/getSupplierRejectionsAsync")
    @Oneway
    @RequestWrapper(localName = "getSupplierRejectionsAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.GetSupplierRejectionsAsync")
    public void getSupplierRejectionsAsync(
        @WebParam(name = "RequestId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        long requestId,
        @WebParam(name = "VendorEmailAddress", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        String vendorEmailAddress);

    /**
     * 
     * @param requestId
     * @param vendorEmailAddress
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.ApSupplierRejections>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/getSupplierRejections")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
    @RequestWrapper(localName = "getSupplierRejections", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.GetSupplierRejections")
    @ResponseWrapper(localName = "getSupplierRejectionsResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.GetSupplierRejectionsResponse")
    public List<ApSupplierRejections> getSupplierRejections(
        @WebParam(name = "RequestId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        long requestId,
        @WebParam(name = "VendorEmailAddress", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        String vendorEmailAddress)
        throws ServiceException
    ;

    /**
     * 
     * @param attachments
     * @param invoiceInterfaceHeader
     * @return
     *     returns com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.InterfaceResponseResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/createInvoiceInterfaceWithAttachments")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
    @RequestWrapper(localName = "createInvoiceInterfaceWithAttachments", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.CreateInvoiceInterfaceWithAttachments")
    @ResponseWrapper(localName = "createInvoiceInterfaceWithAttachmentsResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.CreateInvoiceInterfaceWithAttachmentsResponse")
    public InterfaceResponseResult createInvoiceInterfaceWithAttachments(
        @WebParam(name = "invoiceInterfaceHeader", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        InvoiceInterfaceHeader invoiceInterfaceHeader,
        @WebParam(name = "attachments", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        List<AttachmentDetails> attachments)
        throws ServiceException
    ;

    /**
     * 
     * @param attachments
     * @param invoiceInterfaceHeader
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/createInvoiceInterfaceWithAttachmentsAsync")
    @Oneway
    @RequestWrapper(localName = "createInvoiceInterfaceWithAttachmentsAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/", className = "com.oracle.xmlns.apps.financials.payables.invoices.quickinvoices.invoiceinterfaceservice.types.CreateInvoiceInterfaceWithAttachmentsAsync")
    public void createInvoiceInterfaceWithAttachmentsAsync(
        @WebParam(name = "invoiceInterfaceHeader", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        InvoiceInterfaceHeader invoiceInterfaceHeader,
        @WebParam(name = "attachments", targetNamespace = "http://xmlns.oracle.com/apps/financials/payables/invoices/quickInvoices/invoiceInterfaceService/types/")
        List<AttachmentDetails> attachments);

}
